apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: asia-south1-docker.pkg.dev/chaithu-project-463807/myrepo/backend-app:latest
          ports:
            - containerPort: 5001
