name: cicd-ec2

on:
  push:
    branches:
      - main

jobs:
  build_image_deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Log in to AWS 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.Access_key_id }}  
          aws-secret-access-key: ${{ secrets.Access_key }}  
          aws-region: us-east-1
      - name: Login to AWS ECR
        run: | 
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 869935092862.dkr.ecr.us-east-1.amazonaws.com
      - name: Build Docker image
        run: |
          docker build -t backend ./backend/
          docker build -t frontend ./frontend/
      - name: Push image to DockerHub
        run: |
          docker tag backend:latest 869935092862.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          docker tag frontend:latest 869935092862.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          docker push 869935092862.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          docker push 869935092862.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
      - name: Deploy to EC2 instance
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  
          SSH_USER: ${{ secrets.SSH_USER }}    
          SSH_IP: ${{ secrets.SSH_IP }}
        run: |
          echo "$SSH_KEY" > kartik-key.pem
          sudo chmod 600 kartik-key.pem
          ssh -o StrictHostKeyChecking=no -i kartik-key.pem $SSH_USER@$SSH_IP << 'EOF'
            sudo apt update
            sudo apt upgrade -y
            sudo apt install docker.io -y || true
            sudo systemctl enable docker || true
            sudo systemctl start docker || true
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d  --name mysql-container -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=kartikdatabase  -e MYSQL_USER=kartikuser -e MYSQL_PASSWORD=password -p 3300:3306 mysql:latest || true
            sudo docker pull 869935092862.dkr.ecr.us-east-1.amazonaws.com/backend:latest
            sudo docker pull 869935092862.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
            sudo docker run --name=backend -p 5000:5000 -d 869935092862.dkr.ecr.us-east-1.amazonaws.com/backend:latest
            sudo docker run --name=frontend -p 3000:80 -d 869935092862.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          EOF
